name: nextcoud_favourite_share
description: >-
  A command-line application to share a user's favourite files in NextCloud.
version: 1.0.0
homepage: https://github.com/fkleon/nextcloud-favourite-share

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  nextcloud:
    path: ../dart-nextcloud

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
